import { DatePicker, Input, Textarea } from "ant-design-vue";
import ImageUploader from "@/components/ImageUploader.vue";

export const formConfig = {
  register: [
    {
      label: "样本图片",
      component: ImageUploader,
      value: "picUrl",
      disabled: false,
      hidden: false,
    },
    {
      label: "生物种类",
      component: Input,
      value: "species",
      disabled: false,
      hidden: false,
    },
    {
      label: "物种名称",
      component: Input,
      value: "name",
      disabled: false,
      hidden: false,
    },
    {
      label: "鉴定者",
      component: Input,
      value: "appraiser",
      disabled: false,
      hidden: false,
    },
    {
      label: "保存方式",
      component: Input,
      value: "saveWay",
      disabled: false,
      hidden: false,
    },
    {
      label: "保存地点",
      component: Input,
      value: "savePlace",
      disabled: false,
      hidden: false,
    },
    {
      label: "备注",
      component: Textarea,
      value: "remark",
      disabled: false,
      hidden: false,
    },
  ],
  dispose: [
    {
      label: "样本编号",
      component: Input,
      value: "rid",
      disabled: true,
      hidden: false,
    },
    // {
    //   label: "样本图片",
    //   component: ImageUploader,
    //   value: "picUrl",
    //   disabled: false,
    //   hidden: false,
    // },
    {
      label: "处理方法",
      component: Input,
      value: "disposeWay",
      disabled: false,
      hidden: false,
    },
    {
      label: "处理结果",
      component: Input,
      value: "disposeResult",
      disabled: false,
      hidden: false,
    },
    {
      label: "处理备注",
      component: Input,
      value: "disposeRemark",
      disabled: false,
      hidden: false,
    },
  ],
  delete: [
    {
      label: "样本编号",
      component: Input,
      value: "rid",
      disabled: true,
      hidden: false,
    },
  ],
  quality: [
    {
      label: "样本ID",
      component: Input,
      value: "rid",
      disabled: true,
      hidden: false,
    },
    {
      label: "评估方式",
      component: Input,
      value: "assessWay",
      disabled: false,
      hidden: false,
    },
    {
      label: "评估结果",
      component: Input,
      value: "assessResult",
      disabled: false,
      hidden: false,
    },
    {
      label: "评估备注",
      component: Textarea,
      value: "assessRemark",
      disabled: false,
      hidden: false,
    },
  ],
  destroy: [
    {
      label: "样本编号",
      component: Input,
      value: "rid",
      disabled: true,
      hidden: false,
    },
    {
      label: "销毁方式",
      component: Input,
      value: "destroyedWay",
      disabled: false,
      hidden: false,
    },
    {
      label: "销毁原因",
      component: Input,
      value: "destroyedResult",
      disabled: false,
      hidden: false,
    },
    {
      label: "销毁备注",
      component: Textarea,
      value: "destroyedRemark",
      disabled: false,
      hidden: false,
    },
  ],
  save: [
    {
      label: "样本编号",
      component: Input,
      value: "rid",
      disabled: true,
      hidden: false,
    },
    {
      label: "存储方式",
      component: Input,
      value: "saveWay",
      disabled: false,
      hidden: false,
    },
    {
      label: "存储备注",
      component: Textarea,
      value: "saveRemark",
      disabled: false,
      hidden: false,
    },
  ],
  remove: [
    {
      label: "样本编号",
      component: Input,
      value: "rid",
      disabled: true,
      hidden: false,
    },
    {
      label: "取出方式",
      component: Input,
      value: "removeWay",
      disabled: false,
      hidden: false,
    },
    {
      label: "取出备注",
      component: Textarea,
      value: "removeRemark",
      disabled: false,
      hidden: false,
    },
  ],
  lend: [
    {
      label: "样本编号",
      component: Input,
      value: "rid",
      disabled: true,
      hidden: false,
    },
    {
      label: "借出目的",
      component: Input,
      value: "lendPurpose",
      disabled: false,
      hidden: false,
    },
    {
      label: "借出备注",
      component: Textarea,
      value: "lendRemark",
      disabled: false,
      hidden: false,
    },
    {
      label: "预计归还日期",
      component: DatePicker,
      value: "predictReturnDate",
      disabled: false,
      hidden: false,
    },
  ],
  return: [
    {
      label: "样本编号",
      component: Input,
      value: "rid",
      disabled: true,
      hidden: false,
    },
    {
      label: "归还备注",
      component: Textarea,
      value: "returnRemark",
      disabled: false,
      hidden: false,
    },
  ],
  detail: [
    {
      label: "id",
      component: Input,
      value: "id",
      disabled: true,
      hidden: true,
    },
    {
      label: "样本编号",
      component: Input,
      value: "rid",
      disabled: true,
      hidden: false,
    },
    {
      label: "存储编号",
      component: Input,
      value: "sid",
      disabled: true,
      hidden: false,
    },
    {
      label: "操作人员编号",
      component: Input,
      value: "uid",
      disabled: true,
      hidden: false,
    },
    {
      label: "存储方式",
      component: Input,
      value: "saveWay",
      disabled: true,
      hidden: false,
    },
    {
      label: "存储备注",
      component: Input,
      value: "saveRemark",
      disabled: true,
      hidden: false,
    },
    {
      label: "取出原因",
      component: Input,
      value: "removeResult",
      disabled: true,
      hidden: false,
    },
    {
      label: "取出备注",
      component: Input,
      value: "removeRemark",
      disabled: true,
      hidden: false,
    },
    {
      label: "借出目的",
      component: Input,
      value: "lendResult",
      disabled: true,
      hidden: false,
    },
    {
      label: "借出备注",
      component: Input,
      value: "lendRemark",
      disabled: true,
      hidden: false,
    },
    {
      label: "预计归还时间",
      component: Input,
      value: "predictReturnDate",
      disabled: true,
      hidden: false,
    },
    {
      label: "归还备注",
      component: Input,
      value: "returnRemark",
      disabled: true,
      hidden: false,
    },
    {
      label: "销毁方式",
      component: Input,
      value: "destroyedWay",
      disabled: true,
      hidden: false,
    },
    {
      label: "销毁原因",
      component: Input,
      value: "destroyedResult",
      disabled: true,
      hidden: false,
    },
    {
      label: "销毁备注",
      component: Input,
      value: "destroyedRemark",
      disabled: true,
      hidden: false,
    },
    {
      label: "样本状态", // 样本状态：1：存储，2：取出，3：借出，4：归还，5：销毁/tinyint(4)
      component: Input,
      value: "state",
      disabled: true,
      hidden: false,
    },
    {
      label: "删除状态",
      component: Input,
      value: "isDelete",
      disabled: true,
      hidden: true,
    },
    {
      label: "创建时间",
      component: Input,
      value: "createTime",
      disabled: true,
      hidden: false,
    },
    {
      label: "更新时间",
      component: Input,
      value: "updateTime",
      disabled: true,
      hidden: false,
    },
  ],
};
